const CHANGE_TO_DEMAND = 'CHANGE_TO_DEMAND';
const CHANGE_TO_ABOUT_US = 'CHANGE_TO_ABOUT_US';
const GET_CITIES = 'GET_CITIES';
const GET_SCHOOLS = 'GET_SCHOOLS';
const GET_SPACES = 'GET_SPACES';
const GET_ACTIVITIES = 'GET_ACTIVITIES';
const GET_PEOPLES = 'GET_PEOPLES';
const SUBMIT_DEMAND = 'SUBMIT_DEMAND';
const CHANGE_TO_LOGIN = 'CHANGE_TO_LOGIN';
const CHANGE_TO_REGISTER = 'CHANGE_TO_REGISTER';
const CHANGE_TO_PASSWORD = 'CHANGE_TO_PASSWORD';
const TO_LOGIN = 'TO_LOGIN';
const TO_REGISTER = 'TO_REGISTER';
const TO_PASSWORD = 'TO_PASSWORD';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
const GET_PHONE_CODE = 'GET_PHONE_CODE';
const GET_PUBLIC_PLACES = 'GET_PUBLIC_PLACES';
const SET_ACTIVE_INDEX = 'SET_ACTIVE_INDEX';
const GET_CASES_LIST = 'GET_CASES_LIST';
const GET_CASE_DETAIL = 'GET_CASE_DETAIL';
const RESET_SEARCH_OBJ = 'RESET_SEARCH_OBJ';
const RESET_DEMAND_FORM = 'RESET_DEMAND_FORM';
const GET_MY_INFO = 'GET_MY_INFO';
const DO_SEARCH_SPACES = 'DO_SEARCH_SPACES';
const GET_SPACE_DETAIL = 'GET_SPACE_DETAIL';
const RESET_LOGIN_FORM = 'RESET_LOGIN_FORM';
const RESET_REGISTER_FORM = 'RESET_REGISTER_FORM';
const RESET_PASSWORD_FORM = 'RESET_PASSWORD_FORM';
const RESET_USER_COMMON_SHOW = 'RESET_USER_COMMON_SHOW';
const UPDATE_MY_INFO = 'UPDATE_MY_INFO';
const GET_MY_DEMAND = 'GET_MY_DEMAND';

export default {
  CHANGE_TO_DEMAND,
  CHANGE_TO_ABOUT_US,
  GET_CITIES,
  GET_SCHOOLS,
  GET_SPACES,
  GET_ACTIVITIES,
  GET_PEOPLES,
  SUBMIT_DEMAND,
  CHANGE_TO_LOGIN,
  CHANGE_TO_REGISTER,
  CHANGE_TO_PASSWORD,
  TO_LOGIN,
  TO_REGISTER,
  TO_PASSWORD,
  CHANGE_PASSWORD,
  GET_PHONE_CODE,
  GET_PUBLIC_PLACES,
  SET_ACTIVE_INDEX,
  GET_CASES_LIST,
  GET_CASE_DETAIL,
  RESET_SEARCH_OBJ,
  RESET_DEMAND_FORM,
  GET_MY_INFO,
  DO_SEARCH_SPACES,
  GET_SPACE_DETAIL,
  RESET_LOGIN_FORM,
  RESET_REGISTER_FORM,
  RESET_PASSWORD_FORM,
  RESET_USER_COMMON_SHOW,
  UPDATE_MY_INFO,
  GET_MY_DEMAND,
}
